config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :users, only: :show do
    resources :pickups, only: :index
    resources :inventories, only: :index
    resources :pastinventories, only: :index
    resources :pastpickups, only: :index
  end

  resources :inventories, only: [:index, :show]

  resources :available, only: :index
  resources :nearme, only: :index

  resources :stores, only: :index
  resources :shelters, only: :index
  resources :testimonials, only: :index
  resources :comments, only: [:edit]

  namespace :api do
    namespace :v1 do
      resources :inventories, except: [:new, :edit, :destroy]
      resources :pickups, except: [:show, :new, :edit]
      resources :pastinventories, only: :index
      resources :pastpickups, only: :index
      resources :comments, except: [:index, :new, :edit]
      resources :currentuser, only: :index
      resources :nearmeinventories, only: :index
      resources :availableinventories, only: :index
    end
  end

  get '*path', to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :user
  belongs_to :inventory
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  validates :quantity, numericality: { greater_than: 0 }
  validates :item, presence: true
  validates :available, inclusion: { in: [true, false] }
  validates :active, inclusion: { in: [true, false] }

  belongs_to :user
  has_many :comments
  belongs_to :pickup, optional: true

  def self.search(search)
    where("item ILIKE ?", "%#{search}%")
  end

  # Iterate through active inventory and mark any not from today as inactive
  def self.check_active
    active_inventory= Inventory.where(active: true)
    active_inventory.each do |inventory|
      inventory.active = false if inventory.created_at.to_date != DateTime.now.to_date
      inventory.save
    end
  end
end

app/models/pickup.rb
class Pickup < ApplicationRecord
  belongs_to :store, foreign_key: 'store_id', class_name: 'User'
  belongs_to :shelter, foreign_key: 'shelter_id', class_name: 'User'
end

app/models/shelter.rb
class Shelter < User
end

app/models/store.rb
class Store < User
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :strip_phone

  def strip_phone
    if self.phone
      self.phone.gsub!(/\D/, '')
    end
  end

  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, inclusion: { in: STATES, message: 'can\'t be blank' }
  validates :zip, presence: true, numericality: true, length: { is: 5,
    message: 'must have a length of 5' }
  validates :phone, allow_blank: true, numericality: true, length: { in: 10..11 }
  validates :type, inclusion: { in: TYPES_COLLECTION,
    message: 'can\'t be blank' }
  validates :email, email: true,
    uniqueness: { message: "An account already exists for that email address!" }

  def store?
    self.type == 'Store'
  end

  def shelter?
    self.type == 'Shelter'
  end

  has_many :inventories
  has_many :comments
  has_many :stores, through: :store_pickups, source: :store
  has_many :store_pickups, foreign_key: :shelter_id, class_name: 'User'
  has_many :shelters, through: :shelter_pickups, source: :shelter
  has_many :shelter_pickups, foreign_key: :store_id, class_name: 'User'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/pickups_controller.rb
class Api::V1::PickupsController < ApplicationController
  def index
    # Iterate through pickups for user and make sure any inventory not from
    # today is marked as inactive
    @user_id = current_user.id
    @user_pickups = Pickup.where(shelter_id: @user_id)
    @user_pickups.each do |pickup|
      pickup.active = false if pickup.inventory.created_at.to_date != DateTime.now.to_date
      pickup.save
    end
    @active_pickups = Pickup.where(shelter_id: @user_id, active: true)
    # Serve up the active pickup items
    render json: @active_pickups
  end

  def create
    body = request.body.read
    parsed = JSON.parse(body)
    pickup = Pickup.new(parsed)
    # Save pickup
    if pickup.save
      # Add pickup_id to appropriate inventory item
      pickup.inventory.pickup_id = pickup.id
      pickup.inventory.available = false
      if pickup.inventory.save
        render json: { messages: 'Success', pickup: pickup }
      end
    else
      render json: { messages: pickup.errors.full_messages }
    end
  end

  def destroy
    body = request.body.read
    parsed = JSON.parse(body)
    pickup = Pickup.find(parsed['pickup_id'])
    # Reset related inventory object
    pickup.inventory.pickup_id = nil
    pickup.inventory.available = true
    pickup.inventory.save
    # Destroy pickup object
    pickup.destroy
    render json: { message: 'Success' }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  before_filter :configure_permitted_parameters, if: :devise_controller?

 protected

  def after_sign_in_path_for(resource)
    if current_user.store?
      user_inventories_path(current_user.id)
    elsif current_user.shelter?
      user_pickups_path(current_user.id)
    else
      root_path
    end
  end

  def after_sign_up_path_for(resource)
    if current_user.store?
      user_inventories_path(current_user.id)
    elsif current_user.shelter?
      user_pickups_path(current_user.id)
    else
      root_path
    end
  end

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :city,
     :state, :zip, :phone, :type])
 end
end

app/controllers/available_controller.rb
class AvailableController < ApplicationController
  def index
    @available_inventories = Inventory.where(available: true, active: true)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def edit; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @inventories = Inventory.all
    if params[:search]
      @inventories = Inventory.search(params[:search]).order("created_at DESC")
    else
      @inventories = Inventory.all.order("created_at DESC")
    end
  end

  def show; end
end

app/controllers/nearme_controller.rb
class NearmeController < ApplicationController
  def index; end
end

app/controllers/pastinventories_controller.rb
class PastinventoriesController < ApplicationController
  def index; end
end

app/controllers/pastpickups_controller.rb
class PastpickupsController < ApplicationController
  def index; end
end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  def index; end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index; end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_errors(object, field_name)
    error_array = []
    if object.errors.any?
      object.errors.full_messages.each do |error|
        if error.include?(field_name)
          error_array << error
        end
      end
      return error_array.join(", ")
    end
    return nil
  end
end

app/views/available/index.html.erb
<div class='topbar-border'></div>

<h1>Available Inventory</h1>
<% @available_inventories.each do |inventory| %>
  <div class='row inventory-tile-container align-center'>
    <div class="small-10 small-centered columns inventory-tile green-outline">
      <a href="/inventories/<%= inventory.id %>" class='black-text'>
        <h2> <span class='strong'>Item:</span> <%= inventory.item %> </h2>
        <p> Quantity: <%= inventory.quantity %> </p>
        <% if inventory.measurement %>
          <p> Measurement: <%= inventory.measurement %> </p>
        <% end %>
      </a>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div class='landing-photo'>
  <img data-interchange="[ <%= asset_path('small1000w.jpg') %>, small], [ <%= asset_path('medium2500w.jpg') %>, medium], [ <%= asset_path('medium2500w.jpg') %>, large]" />
</div>

<div class='row info-tiles align-spaced'>
  <div class="card info-tile text-center small-centered" style="width: 300px;">
    <div class="card-section">
      <h1><span class='green-text'>Waste</span> <span class='black-text'>Not</span></h1>
      <hr />
      <h2>Show your Available Inventory</h2>
      <%= button_to "Stores", stores_path, class: 'button info-button' %>
    </div>
  </div>
  <div class="card info-tile text-center small-centered" style="width: 300px;">
    <div class="card-section">
      <h1><span class='green-text'>Share</span></h1>
      <hr />
      <h2>Share <br/>your <br/> Resources</h2>
      <%= button_to "See Testimonials", testimonials_path, class: 'button info-button' %>
    </div>
  </div>
  <div class="card info-tile text-center small-centered" style="width: 300px;">
    <div class="card-section">
      <h1><span class='green-text'>Want</span> <span class='black-text'>Not</span></h1>
      <hr />
      <h2>Schedule Pickups of Available Food</h2>
      <%= button_to "Shelters", shelters_path, class: 'button info-button' %>
    </div>
  </div>
</div>

app/views/nearme/index.html.erb
<div id='app' />